# Generated by Django 4.2.2 on 2023-08-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_fabricacion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricacion',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
