# Generated by Django 4.2.2 on 2023-10-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_fabricacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_prima',
            name='stock',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Stock de Materia Prima')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('valor_total_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total de la Compra')),
                ('materia_prima', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.materia_prima')),
            ],
            options={
                'verbose_name_plural': 'Stocks de Materia Prima',
            },
        ),
    ]
