# Generated by Django 4.2.2 on 2023-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_materia_prima_stock_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia_prima',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock de Materia Prima'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
