# Generated by Django 4.2.2 on 2023-10-07 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_materia_prima_precio_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_prima',
            name='precio_unidad',
        ),
        migrations.AddField(
            model_name='materia_prima',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Precio Unitario'),
        ),
    ]
