# Generated by Django 4.2.2 on 2023-10-26 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_remove_materia_prima_precio_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricacion',
            name='cantidad_materia',
        ),
        migrations.RemoveField(
            model_name='fabricacion',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='fabricacion',
            name='materia_prima',
        ),
        migrations.CreateModel(
            name='Fabricaicon_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('cantidad_producto', models.PositiveIntegerField(default=0, help_text='La cantidad tiene que ser menor a 100', validators=[django.core.validators.MaxValueValidator(100)])),
                ('cantidad_materia', models.PositiveIntegerField(default=0, help_text='cantidad utilizada para hacer el producto', validators=[django.core.validators.MaxValueValidator(100)])),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.materia_prima', verbose_name='Materia Prima')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
