# Generated by Django 4.2.2 on 2023-10-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_remove_fabricacion_cantidad_materia_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabricaicon_detalle',
            new_name='Fabricacion_detalle',
        ),
    ]
