# Generated by Django 4.2.2 on 2023-10-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_rename_fabricaicon_detalle_fabricacion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricacion_detalle',
            name='fabricacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.fabricacion', verbose_name='Fabricacion'),
            preserve_default=False,
        ),
    ]
