# Generated by Django 4.2 on 2023-08-07 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('numero_documento', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='numero_documento_set', to=settings.AUTH_USER_MODEL, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='Número de Documento')),
                ('tipo_documento', models.OneToOneField(choices=[('CC ', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], default='CC ', max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_documento_set', to=settings.AUTH_USER_MODEL, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
