# Generated by Django 4.2.2 on 2023-09-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_compra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detalle_compra',
            name='valor_total',
        ),
    ]
