# Generated by Django 4.2.2 on 2023-10-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_remove_detalle_compra_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compra.compra', verbose_name='Compra'),
            preserve_default=False,
        ),
    ]
