# Generated by Django 4.2.2 on 2023-10-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_detalle_compra_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_compra',
            old_name='precio_unidad',
            new_name='precio_unitario',
        ),
    ]
