# Generated by Django 4.2.2 on 2023-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_rename_precio_unitario_detalle_compra_precio_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
