# Generated by Django 4.2.2 on 2023-10-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_detalle_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
