# Generated by Django 4.2.2 on 2023-10-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='calcular_costo_fabricacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Fabricación'),
        ),
    ]
