# Generated by Django 4.2.2 on 2023-11-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_calcular_costo_fabricacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='calcular_costo_fabricacion',
            new_name='costo_fabricacion',
        ),
    ]
