# Generated by Django 4.2.2 on 2023-08-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={'verbose_name_plural': 'Detalles Venta'},
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
