# Generated by Django 4.2.2 on 2023-10-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_venta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
