# Generated by Django 4.2.2 on 2023-10-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_detalle_venta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='valor_total',
        ),
    ]
