# Generated by Django 4.2.2 on 2023-10-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_persona_user_alter_persona_numero_documento_and_more'),
        ('venta', '0006_detalle_venta_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='persona_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_cliente', to='usuario.persona', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='persona_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_vendedor', to='usuario.persona', verbose_name='Vendedor'),
        ),
    ]
